spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d5qd33shg0os73ca9vb0-a.virginia-postgres.render.com/back_ecomerce}
spring.datasource.username=${DB_USERNAME:back_ecomerce_user}
spring.datasource.password=${DB_PASSWORD:CMUymqZ0mgB9f5CNIFNYlWremyYXJ310}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true